### ISSUE TITLE
Azure Stack - Application Insights?

### ISSUE THREAD

**Issue by cloudarchitectfrank** [MicrosoftDocs/hybrid#6]
[Enter feedback here]

It is not clear from this article where you are deploying Application Insights instance. Is this deployed in Azure Stack Hub or in Azure or both?

Thanks
cloudarchitectfrank@outlook.com 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26703b13-c7f5-388f-137b-5582a85edaaf
* Version Independent ID: 09d6e819-1b12-7ac2-0860-dc320edebae8
* Content: [Deploy hybrid app with on-premises data that scales cross-cloud - Azure Hybrid App Solutions](https://docs.microsoft.com/en-us/hybrid/app-solutions/solution-deployment-guide-cross-cloud-scaling-onprem-data)
* Content Source: [hybrid/app-solutions/solution-deployment-guide-cross-cloud-scaling-onprem-data.md](https://github.com/MicrosoftDocs/hybrid/blob/master/hybrid/app-solutions/solution-deployment-guide-cross-cloud-scaling-onprem-data.md)
* Service: **multiple**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by BryanLa** [comment]
@cloudarchitectfrank - thanks very much for your feedback.

In this case, Application Insights is configured in Azure. Check out the [the corresponding pattern](https://docs.microsoft.com/hybrid/app-solutions/pattern-cross-cloud-scale-onprem-data#solution) for this solution, and you'll see this called out in the "Solution" and "Components" sections. 

Here's a great video as well, that [talks about the architecture at 1:49](https://youtu.be/2lw8zOpJTn0?t=109), and highlights the use of Application Insights in the Azure layer. It goes into more detail on the use of Application Insights starting at 2:56.

I'll update the solution example doc as well to make this clearer.

cc: @anjayajodha, @garvitarai 

#please-close
